// Every theme in one place: its name, category and swatch for the picker. The holiday themes are fully described
// here (colours, falling or rising emoji, logo) and their CSS is generated by holidayCss(), so the React app and
// the phone artifact get exactly the same themes from one definition.

export const CATEGORIES = [
  { id: 'everyday', name: 'Everyday' },
  { id: 'nature', name: 'Nature' },
  { id: 'fun', name: 'Fun' },
  { id: 'holidays', name: 'Holidays' },
]

// Holidays, in the order they come round in the year. `motion`: 'fall' drifts down, 'rise' floats up.
export const HOLIDAYS = [
  {
    id: 'newyear', name: "New Year's", dark: true,
    bg: '#0b0f1f', card: '#151b36', text: '#f5efe0', muted: '#a9afc8', line: '#2a3157', soft: '#1d2547',
    brand: '#f2c14e', brand2: '#c0c6e0', ink: '#1b1500', cta: '#f2c14e', cta2: '#ffe08a', ctaInk: '#1b1500',
    stripe: ['#f2c14e', '#ffffff', '#c0c6e0', '#f2c14e'], emoji: ['🎉', '✨', '🥂', '🎆', '🎊'], motion: 'fall', logo: '🥂',
  },
  {
    id: 'lunar', name: 'Lunar New Year',
    bg: '#fff3e6', card: '#fffaf3', text: '#3b0d0d', muted: '#8a5548', line: '#f2d5ba', soft: '#ffe3cc',
    brand: '#c8102e', brand2: '#f2a900', ink: '#ffffff', cta: '#c8102e', cta2: '#d2441a', ctaInk: '#ffffff',
    stripe: ['#c8102e', '#f2a900', '#c8102e'], emoji: ['🏮', '🧧', '🐉', '🌸', '🎆'], motion: 'fall', logo: '🏮',
  },
  {
    id: 'valentine', name: "Valentine's Day",
    bg: '#fff0f4', card: '#fffafb', text: '#4a1226', muted: '#98586c', line: '#f8cfdb', soft: '#ffdfe8',
    brand: '#bf1c51', brand2: '#ff7a9c', ink: '#ffffff', cta: '#c81e55', cta2: '#d02a60', ctaInk: '#ffffff',
    stripe: ['#ff7a9c', '#c81e55', '#ff7a9c'], emoji: ['❤️', '💗', '💕', '🌹', '💘'], motion: 'rise', logo: '💝',
  },
  {
    id: 'stpatrick', name: "St. Patrick's Day",
    bg: '#eef8ee', card: '#fbfffb', text: '#0f3a1a', muted: '#4a7553', line: '#cde8d0', soft: '#dff1e1',
    brand: '#1b7a34', brand2: '#e0a800', ink: '#ffffff', cta: '#1b7a34', cta2: '#1a8236', ctaInk: '#ffffff',
    stripe: ['#1b7a34', '#e0a800', '#1b7a34'], emoji: ['☘️', '🍀', '🌈', '🪙', '🎩'], motion: 'fall', logo: '☘️',
  },
  {
    id: 'easter', name: 'Easter',
    bg: '#fbf5ff', card: '#fffdff', text: '#38274a', muted: '#76628e', line: '#e8daf2', soft: '#efe3fb',
    brand: '#7646c8', brand2: '#ff9ec1', ink: '#ffffff', cta: '#7c4dcc', cta2: '#a2479e', ctaInk: '#ffffff',
    stripe: ['#ff9ec1', '#ffd166', '#9fe3c3', '#9ec5ff', '#c8a8f0'], emoji: ['🐣', '🥚', '🌷', '🐰', '🌸'], motion: 'fall', logo: '🐣',
  },
  {
    id: 'july4', name: '4th of July',
    bg: '#f4f7ff', card: '#ffffff', text: '#0b1d4a', muted: '#566690', line: '#d3dcf2', soft: '#e3eafb',
    brand: '#1d3a8a', brand2: '#d32f2f', ink: '#ffffff', cta: '#c62828', cta2: '#c9402a', ctaInk: '#ffffff',
    stripe: ['#d32f2f', '#1d3a8a', '#d32f2f', '#1d3a8a'], emoji: ['🎆', '🎇', '⭐', '🇺🇸', '✨'], motion: 'rise', logo: '🎆',
  },
  {
    id: 'thanksgiving', name: 'Thanksgiving',
    bg: '#fff3e3', card: '#fffaf1', text: '#3a2210', muted: '#7a5a3c', line: '#efd8ba', soft: '#fbe4c6',
    brand: '#a84a14', brand2: '#d99a1a', ink: '#ffffff', cta: '#a84a14', cta2: '#b45a14', ctaInk: '#ffffff',
    stripe: ['#a84a14', '#d99a1a', '#7a3b12'], emoji: ['🍂', '🍁', '🌽', '🥧', '🦃'], motion: 'fall', logo: '🦃',
  },
  {
    id: 'christmas', name: 'Christmas', dark: true,
    bg: '#0d2418', card: '#143323', text: '#f6f1e7', muted: '#a9c4b2', line: '#25513a', soft: '#16392a',
    brand: '#ff6b6b', brand2: '#f5c542', ink: '#2a0508', cta: '#ff6b6b', cta2: '#ff9a6b', ctaInk: '#2a0508',
    stripe: ['#ff6b6b', '#2fb36b', '#f5c542', '#ff6b6b'], emoji: ['❄️', '🎄', '⭐', '🎁', '❄️'], motion: 'fall', logo: '🎄',
  },
]

// Themes that existed before the holidays, with their own special effects (those live in the app code).
const BASE_THEMES = [
  { id: 'auto', name: 'Match device', category: 'everyday', colors: ['#f3f6f1', '#2c6e4d', '#0b130f'] },
  { id: 'light', name: 'Light', category: 'everyday', colors: ['#f3f6f1', '#2c6e4d', '#15211a'] },
  { id: 'dark', name: 'Dark', category: 'everyday', colors: ['#0b130f', '#5fd39b', '#e8f1ea'] },
  { id: 'ocean', name: 'Ocean', category: 'nature', colors: ['#eaf6f8', '#087f92', '#07313c'] },
  { id: 'forest', name: 'Forest', category: 'nature', colors: ['#0e1913', '#6fcf8c', '#e5f0e7'] },
  { id: 'sunset', name: 'Sunset', category: 'nature', colors: ['#fff3ee', '#d93f57', '#3a1620'] },
  { id: 'science', name: 'Science', category: 'fun', colors: ['#06121c', '#22e6d4', '#e6fbff'] },
  { id: 'tropical', name: 'Tropical', category: 'fun', colors: ['#fff6e0', '#d6246e', '#ff9a1f'] },
  { id: 'halloween', name: 'Halloween', category: 'holidays', colors: ['#150c20', '#ff8a1f', '#f7ead9'], after: 'july4' },
]

// Every theme for the picker, grouped by category; Halloween sits in the holiday list where it falls in the year.
export const THEMES = (() => {
  const holidays = HOLIDAYS.map((h) => ({ id: h.id, name: h.name, category: 'holidays', colors: [h.bg, h.brand, h.text] }))
  const halloween = BASE_THEMES.find((t) => t.id === 'halloween')
  holidays.splice(holidays.findIndex((t) => t.id === halloween.after) + 1, 0, halloween)
  return [...BASE_THEMES.filter((t) => t.id !== 'halloween'), ...holidays]
})()

// ---- "in season": which holiday themes fit today's date ----
// Each holiday has a day it falls on (for some it moves: Easter, Thanksgiving, Lunar New Year) and how many days
// before and after it counts as in season.
const LUNAR_NEW_YEAR = { // from 2025; beyond this table the badge simply isn't shown for it
  2025: [0, 29], 2026: [1, 17], 2027: [1, 6], 2028: [0, 26], 2029: [1, 13], 2030: [1, 3], 2031: [0, 23], 2032: [1, 11],
  2033: [0, 31], 2034: [1, 19], 2035: [1, 8], 2036: [0, 28], 2037: [1, 15], 2038: [1, 4], 2039: [0, 24], 2040: [1, 12],
}

/** Easter Sunday (the Gregorian calendar's standard calculation). */
export function easterDate(year) {
  const a = year % 19, b = Math.floor(year / 100), c = year % 100
  const d = Math.floor(b / 4), e = b % 4, f = Math.floor((b + 8) / 25), g = Math.floor((b - f + 1) / 3)
  const h = (19 * a + b - d - g + 15) % 30, i = Math.floor(c / 4), k = c % 4
  const l = (32 + 2 * e + 2 * i - h - k) % 7, m = Math.floor((a + 11 * h + 22 * l) / 451)
  const month = Math.floor((h + l - 7 * m + 114) / 31), day = ((h + l - 7 * m + 114) % 31) + 1
  return new Date(year, month - 1, day)
}

/** US Thanksgiving: the fourth Thursday of November. */
export function thanksgivingDate(year) {
  const firstThursday = 1 + ((4 - new Date(year, 10, 1).getDay() + 7) % 7)
  return new Date(year, 10, firstThursday + 21)
}

export const SEASONS = {
  newyear: { date: (y) => new Date(y, 0, 1), before: 5, after: 1 }, // Dec 27 to Jan 2
  lunar: { date: (y) => (LUNAR_NEW_YEAR[y] ? new Date(y, LUNAR_NEW_YEAR[y][0], LUNAR_NEW_YEAR[y][1]) : null), before: 7, after: 15 },
  valentine: { date: (y) => new Date(y, 1, 14), before: 7, after: 1 },
  stpatrick: { date: (y) => new Date(y, 2, 17), before: 7, after: 1 },
  easter: { date: easterDate, before: 14, after: 1 },
  july4: { date: (y) => new Date(y, 6, 4), before: 7, after: 1 },
  halloween: { date: (y) => new Date(y, 9, 31), before: 30, after: 1 }, // all of October
  thanksgiving: { date: thanksgivingDate, before: 10, after: 1 },
  christmas: { date: (y) => new Date(y, 11, 25), before: 24, after: 1 }, // Dec 1 to Dec 26
}

/** Is this holiday theme in season on `now`? Checks last year's, this year's and next year's date, so New Year's works across Dec/Jan. */
export function inSeason(id, now = new Date()) {
  const season = SEASONS[id]
  if (!season) return false
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())
  const DAY_MS = 24 * 60 * 60 * 1000
  for (const y of [today.getFullYear() - 1, today.getFullYear(), today.getFullYear() + 1]) {
    const day = season.date(y)
    if (!day) continue
    const days = Math.round((today - day) / DAY_MS)
    if (days >= -season.before && days <= season.after) return true
  }
  return false
}

export const inSeasonIds = (now = new Date()) => Object.keys(SEASONS).filter((id) => inSeason(id, now))

export const themesIn = (category) => THEMES.filter((t) => t.category === category)
export const holidayById = (id) => HOLIDAYS.find((h) => h.id === id)

const STATUS_LIGHT = { ok: '#1b7a3d', okBg: '#e0f5dd', warn: '#8a5300', warnBg: '#fff0c7', warnLine: '#f0b84a', info: '#07696f', infoBg: '#dcf4f1' }
const STATUS_DARK = { ok: '#5dffb0', okBg: '#0e3a2f', warn: '#ffd166', warnBg: '#3a2a0c', warnLine: '#a07a1a', info: '#8fd8ff', infoBg: '#11344d' }
export const STATUS = { light: STATUS_LIGHT, dark: STATUS_DARK }

/** CSS for every holiday theme. Sets both apps' variable names (the React app's and the artifact's). */
export function holidayCss() {
  return HOLIDAYS.map((h) => {
    const s = h.dark ? STATUS_DARK : STATUS_LIGHT
    const root = `:root[data-skin='${h.id}']`
    return `
${root} {
  --bg: ${h.bg}; --card: ${h.card}; --surface: ${h.card}; --text: ${h.text}; --ink: ${h.text}; --muted: ${h.muted}; --line: ${h.line}; --soft: ${h.soft};
  --brand: ${h.brand}; --accent: ${h.brand}; --brand-2: ${h.brand2}; --accent-2: ${h.brand2}; --brand-ink: ${h.ink}; --accent-ink: ${h.ink};
  --cta: ${h.cta}; --cta-2: ${h.cta2}; --cta-ink: ${h.ctaInk};
  --grid: color-mix(in srgb, ${h.brand} 9%, transparent); --hi: color-mix(in srgb, ${h.brand2} 28%, ${h.card});
  --ok: ${s.ok}; --ok-bg: ${s.okBg}; --warn: ${s.warn}; --warn-bg: ${s.warnBg}; --warn-line: ${s.warnLine}; --info: ${s.info}; --info-bg: ${s.infoBg};
  --shadow: ${h.dark ? '0 10px 28px rgba(0, 0, 0, .5)' : `0 10px 28px color-mix(in srgb, ${h.brand} 16%, transparent)`};
  --logo: "${h.logo}"; color-scheme: ${h.dark ? 'dark' : 'light'};
}
${root} body {
  background-image: radial-gradient(520px 380px at 100% 0%, color-mix(in srgb, ${h.brand2} ${h.dark ? 13 : 24}%, transparent), transparent 70%), radial-gradient(480px 420px at 0% 100%, color-mix(in srgb, ${h.brand} ${h.dark ? 9 : 16}%, transparent), transparent 70%);
  background-size: auto, auto; background-attachment: fixed;
}
${root} .top, ${root} header.top { border-bottom: 4px solid transparent; border-image: linear-gradient(90deg, ${h.stripe.join(', ')}) 1; }
${root} .logo-mark { background: transparent; font-size: 0; box-shadow: none; }
${root} .logo-mark svg { display: none; }
${root} .logo-mark::after { content: var(--logo); display: inline-block; font-size: 1.7rem; line-height: 1; transform-origin: 50% 90%; animation: pine-sway 3.6s ease-in-out infinite alternate; }
${root} .answer { background: linear-gradient(135deg, color-mix(in srgb, ${h.brand2} 24%, ${h.card}), color-mix(in srgb, ${h.brand} 14%, ${h.card})); }`
  }).join('\n') + `
@media (prefers-reduced-motion: reduce) { .hparts { display: none; } :root[data-skin] .logo-mark::after { animation: none; } }
`
}
