// Every theme in one place: its name, category and swatch for the picker. The holiday themes are fully described
// here (colours, falling or rising emoji, logo) and their CSS is generated by holidayCss(), so the React app and
// the phone artifact get exactly the same themes from one definition.

export const CATEGORIES = [
  { id: 'everyday', name: 'Everyday' },
  { id: 'nature', name: 'Nature' },
  { id: 'fun', name: 'Fun' },
  { id: 'holidays', name: 'Holidays' },
]

// Holidays, in the order they come round in the year. `motion`: 'fall' drifts down, 'rise' floats up.
export const HOLIDAYS = [
  {
    id: 'newyear', name: "New Year's", dark: true,
    bg: '#0b0f1f', card: '#151b36', text: '#f5efe0', muted: '#a9afc8', line: '#2a3157', soft: '#1d2547',
    brand: '#f2c14e', brand2: '#c0c6e0', ink: '#1b1500', cta: '#f2c14e', cta2: '#ffe08a', ctaInk: '#1b1500',
    stripe: ['#f2c14e', '#ffffff', '#c0c6e0', '#f2c14e'], emoji: ['🎉', '✨', '🥂', '🎆', '🎊'], motion: 'fall', logo: '🥂',
  },
  {
    id: 'lunar', name: 'Lunar New Year',
    bg: '#fff3e6', card: '#fffaf3', text: '#3b0d0d', muted: '#8a5548', line: '#f2d5ba', soft: '#ffe3cc',
    brand: '#c8102e', brand2: '#f2a900', ink: '#ffffff', cta: '#c8102e', cta2: '#d2441a', ctaInk: '#ffffff',
    stripe: ['#c8102e', '#f2a900', '#c8102e'], emoji: ['🏮', '🧧', '🐉', '🌸', '🎆'], motion: 'fall', logo: '🏮',
  },
  {
    id: 'valentine', name: "Valentine's Day",
    bg: '#fff0f4', card: '#fffafb', text: '#4a1226', muted: '#98586c', line: '#f8cfdb', soft: '#ffdfe8',
    brand: '#bf1c51', brand2: '#ff7a9c', ink: '#ffffff', cta: '#c81e55', cta2: '#d02a60', ctaInk: '#ffffff',
    stripe: ['#ff7a9c', '#c81e55', '#ff7a9c'], emoji: ['❤️', '💗', '💕', '🌹', '💘'], motion: 'rise', logo: '💝',
  },
  {
    id: 'stpatrick', name: "St. Patrick's Day",
    bg: '#eef8ee', card: '#fbfffb', text: '#0f3a1a', muted: '#4a7553', line: '#cde8d0', soft: '#dff1e1',
    brand: '#1b7a34', brand2: '#e0a800', ink: '#ffffff', cta: '#1b7a34', cta2: '#1a8236', ctaInk: '#ffffff',
    stripe: ['#1b7a34', '#e0a800', '#1b7a34'], emoji: ['☘️', '🍀', '🌈', '🪙', '🎩'], motion: 'fall', logo: '☘️',
  },
  {
    id: 'easter', name: 'Easter',
    bg: '#fbf5ff', card: '#fffdff', text: '#38274a', muted: '#76628e', line: '#e8daf2', soft: '#efe3fb',
    brand: '#7646c8', brand2: '#ff9ec1', ink: '#ffffff', cta: '#7c4dcc', cta2: '#a2479e', ctaInk: '#ffffff',
    stripe: ['#ff9ec1', '#ffd166', '#9fe3c3', '#9ec5ff', '#c8a8f0'], emoji: ['🐣', '🥚', '🌷', '🐰', '🌸'], motion: 'fall', logo: '🐣',
  },
  {
    id: 'eid', name: 'Eid', dark: true,
    bg: '#06201f', card: '#0d3230', text: '#f7f0da', muted: '#9fc7bf', line: '#1c4c48', soft: '#12403c',
    brand: '#e6c25a', brand2: '#4fd1c5', ink: '#1a1400', cta: '#e6c25a', cta2: '#f3dc8d', ctaInk: '#1a1400',
    stripe: ['#e6c25a', '#4fd1c5', '#e6c25a'], emoji: ['🌙', '⭐', '✨', '🏮', '🕌'], motion: 'rise', logo: '🌙',
  },
  {
    id: 'july4', name: '4th of July',
    bg: '#f4f7ff', card: '#ffffff', text: '#0b1d4a', muted: '#566690', line: '#d3dcf2', soft: '#e3eafb',
    brand: '#1d3a8a', brand2: '#d32f2f', ink: '#ffffff', cta: '#c62828', cta2: '#c9402a', ctaInk: '#ffffff',
    stripe: ['#d32f2f', '#1d3a8a', '#d32f2f', '#1d3a8a'], emoji: ['🎆', '🎇', '⭐', '🇺🇸', '✨'], motion: 'rise', logo: '🎆',
  },
  {
    id: 'diwali', name: 'Diwali', dark: true,
    bg: '#1b0a26', card: '#2b1239', text: '#fff1d6', muted: '#d2adda', line: '#48235c', soft: '#3a1b4d',
    brand: '#ffb627', brand2: '#ff5e3a', ink: '#2a1400', cta: '#ffb627', cta2: '#ff8a3a', ctaInk: '#2a1400',
    stripe: ['#ffb627', '#ff5e3a', '#e0359b', '#ffb627'], emoji: ['🪔', '✨', '🎇', '🪷', '🏮'], motion: 'rise', logo: '🪔',
  },
  {
    id: 'thanksgiving', name: 'Thanksgiving',
    bg: '#fff3e3', card: '#fffaf1', text: '#3a2210', muted: '#7a5a3c', line: '#efd8ba', soft: '#fbe4c6',
    brand: '#a84a14', brand2: '#d99a1a', ink: '#ffffff', cta: '#a84a14', cta2: '#b45a14', ctaInk: '#ffffff',
    stripe: ['#a84a14', '#d99a1a', '#7a3b12'], emoji: ['🍂', '🍁', '🌽', '🥧', '🦃'], motion: 'fall', logo: '🦃',
  },
  {
    id: 'hanukkah', name: 'Hanukkah',
    bg: '#eef4ff', card: '#ffffff', text: '#0a2660', muted: '#51648f', line: '#d1def5', soft: '#dde8fb',
    brand: '#1c58c0', brand2: '#d9aa2b', ink: '#ffffff', cta: '#1c58c0', cta2: '#2468c8', ctaInk: '#ffffff',
    stripe: ['#1c58c0', '#d9aa2b', '#1c58c0'], emoji: ['🕎', '✡️', '✨', '💙', '🕯️'], motion: 'fall', logo: '🕎',
  },
  {
    id: 'christmas', name: 'Christmas', dark: true,
    bg: '#0d2418', card: '#143323', text: '#f6f1e7', muted: '#a9c4b2', line: '#25513a', soft: '#16392a',
    brand: '#ff6b6b', brand2: '#f5c542', ink: '#2a0508', cta: '#ff6b6b', cta2: '#ff9a6b', ctaInk: '#2a0508',
    stripe: ['#ff6b6b', '#2fb36b', '#f5c542', '#ff6b6b'], emoji: ['❄️', '🎄', '⭐', '🎁', '❄️'], motion: 'fall', logo: '🎄',
  },
]

// Themes that existed before the holidays, with their own special effects (those live in the app code).
const BASE_THEMES = [
  { id: 'auto', name: 'Match device', category: 'everyday', colors: ['#f3f6f1', '#2c6e4d', '#0b130f'] },
  { id: 'light', name: 'Light', category: 'everyday', colors: ['#f3f6f1', '#2c6e4d', '#15211a'] },
  { id: 'dark', name: 'Dark', category: 'everyday', colors: ['#0b130f', '#5fd39b', '#e8f1ea'] },
  { id: 'ocean', name: 'Ocean', category: 'nature', colors: ['#eaf6f8', '#087f92', '#07313c'] },
  { id: 'forest', name: 'Forest', category: 'nature', colors: ['#0e1913', '#6fcf8c', '#e5f0e7'] },
  { id: 'sunset', name: 'Sunset', category: 'nature', colors: ['#fff3ee', '#d93f57', '#3a1620'] },
  { id: 'science', name: 'Science', category: 'fun', colors: ['#06121c', '#22e6d4', '#e6fbff'] },
  { id: 'tropical', name: 'Tropical', category: 'fun', colors: ['#fff6e0', '#d6246e', '#ff9a1f'] },
  { id: 'halloween', name: 'Halloween', category: 'holidays', colors: ['#150c20', '#ff8a1f', '#f7ead9'], after: 'july4' },
]

// Every theme for the picker, grouped by category; Halloween sits in the holiday list where it falls in the year.
export const THEMES = (() => {
  const holidays = HOLIDAYS.map((h) => ({ id: h.id, name: h.name, category: 'holidays', colors: [h.bg, h.brand, h.text] }))
  const halloween = BASE_THEMES.find((t) => t.id === 'halloween')
  holidays.splice(holidays.findIndex((t) => t.id === halloween.after) + 1, 0, halloween)
  return [...BASE_THEMES.filter((t) => t.id !== 'halloween'), ...holidays]
})()

export const themesIn = (category) => THEMES.filter((t) => t.category === category)
export const holidayById = (id) => HOLIDAYS.find((h) => h.id === id)

const STATUS_LIGHT = { ok: '#1b7a3d', okBg: '#e0f5dd', warn: '#8a5300', warnBg: '#fff0c7', warnLine: '#f0b84a', info: '#07696f', infoBg: '#dcf4f1' }
const STATUS_DARK = { ok: '#5dffb0', okBg: '#0e3a2f', warn: '#ffd166', warnBg: '#3a2a0c', warnLine: '#a07a1a', info: '#8fd8ff', infoBg: '#11344d' }
export const STATUS = { light: STATUS_LIGHT, dark: STATUS_DARK }

/** CSS for every holiday theme. Sets both apps' variable names (the React app's and the artifact's). */
export function holidayCss() {
  return HOLIDAYS.map((h) => {
    const s = h.dark ? STATUS_DARK : STATUS_LIGHT
    const root = `:root[data-skin='${h.id}']`
    return `
${root} {
  --bg: ${h.bg}; --card: ${h.card}; --surface: ${h.card}; --text: ${h.text}; --ink: ${h.text}; --muted: ${h.muted}; --line: ${h.line}; --soft: ${h.soft};
  --brand: ${h.brand}; --accent: ${h.brand}; --brand-2: ${h.brand2}; --accent-2: ${h.brand2}; --brand-ink: ${h.ink}; --accent-ink: ${h.ink};
  --cta: ${h.cta}; --cta-2: ${h.cta2}; --cta-ink: ${h.ctaInk};
  --grid: color-mix(in srgb, ${h.brand} 9%, transparent); --hi: color-mix(in srgb, ${h.brand2} 28%, ${h.card});
  --ok: ${s.ok}; --ok-bg: ${s.okBg}; --warn: ${s.warn}; --warn-bg: ${s.warnBg}; --warn-line: ${s.warnLine}; --info: ${s.info}; --info-bg: ${s.infoBg};
  --shadow: ${h.dark ? '0 10px 28px rgba(0, 0, 0, .5)' : `0 10px 28px color-mix(in srgb, ${h.brand} 16%, transparent)`};
  --logo: "${h.logo}"; color-scheme: ${h.dark ? 'dark' : 'light'};
}
${root} body {
  background-image: radial-gradient(520px 380px at 100% 0%, color-mix(in srgb, ${h.brand2} ${h.dark ? 13 : 24}%, transparent), transparent 70%), radial-gradient(480px 420px at 0% 100%, color-mix(in srgb, ${h.brand} ${h.dark ? 9 : 16}%, transparent), transparent 70%);
  background-size: auto, auto; background-attachment: fixed;
}
${root} .top, ${root} header.top { border-bottom: 4px solid transparent; border-image: linear-gradient(90deg, ${h.stripe.join(', ')}) 1; }
${root} .logo-mark { background: transparent; font-size: 0; box-shadow: none; }
${root} .logo-mark svg { display: none; }
${root} .logo-mark::after { content: var(--logo); display: inline-block; font-size: 1.7rem; line-height: 1; transform-origin: 50% 90%; animation: pine-sway 3.6s ease-in-out infinite alternate; }
${root} .answer { background: linear-gradient(135deg, color-mix(in srgb, ${h.brand2} 24%, ${h.card}), color-mix(in srgb, ${h.brand} 14%, ${h.card})); }`
  }).join('\n') + `
@media (prefers-reduced-motion: reduce) { .hparts { display: none; } :root[data-skin] .logo-mark::after { animation: none; } }
`
}
